package com.zxm.graduatemanagesystem.model;

import java.util.ArrayList;
import java.util.List;

public class CompanyInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_info
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_info
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company_info
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public CompanyInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_info
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andComNameIsNull() {
            addCriterion("com_name is null");
            return (Criteria) this;
        }

        public Criteria andComNameIsNotNull() {
            addCriterion("com_name is not null");
            return (Criteria) this;
        }

        public Criteria andComNameEqualTo(String value) {
            addCriterion("com_name =", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotEqualTo(String value) {
            addCriterion("com_name <>", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameGreaterThan(String value) {
            addCriterion("com_name >", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameGreaterThanOrEqualTo(String value) {
            addCriterion("com_name >=", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameLessThan(String value) {
            addCriterion("com_name <", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameLessThanOrEqualTo(String value) {
            addCriterion("com_name <=", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameLike(String value) {
            addCriterion("com_name like", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotLike(String value) {
            addCriterion("com_name not like", value, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameIn(List<String> values) {
            addCriterion("com_name in", values, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotIn(List<String> values) {
            addCriterion("com_name not in", values, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameBetween(String value1, String value2) {
            addCriterion("com_name between", value1, value2, "comName");
            return (Criteria) this;
        }

        public Criteria andComNameNotBetween(String value1, String value2) {
            addCriterion("com_name not between", value1, value2, "comName");
            return (Criteria) this;
        }

        public Criteria andComPersonIsNull() {
            addCriterion("com_person is null");
            return (Criteria) this;
        }

        public Criteria andComPersonIsNotNull() {
            addCriterion("com_person is not null");
            return (Criteria) this;
        }

        public Criteria andComPersonEqualTo(String value) {
            addCriterion("com_person =", value, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonNotEqualTo(String value) {
            addCriterion("com_person <>", value, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonGreaterThan(String value) {
            addCriterion("com_person >", value, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonGreaterThanOrEqualTo(String value) {
            addCriterion("com_person >=", value, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonLessThan(String value) {
            addCriterion("com_person <", value, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonLessThanOrEqualTo(String value) {
            addCriterion("com_person <=", value, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonLike(String value) {
            addCriterion("com_person like", value, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonNotLike(String value) {
            addCriterion("com_person not like", value, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonIn(List<String> values) {
            addCriterion("com_person in", values, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonNotIn(List<String> values) {
            addCriterion("com_person not in", values, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonBetween(String value1, String value2) {
            addCriterion("com_person between", value1, value2, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPersonNotBetween(String value1, String value2) {
            addCriterion("com_person not between", value1, value2, "comPerson");
            return (Criteria) this;
        }

        public Criteria andComPhoneIsNull() {
            addCriterion("com_phone is null");
            return (Criteria) this;
        }

        public Criteria andComPhoneIsNotNull() {
            addCriterion("com_phone is not null");
            return (Criteria) this;
        }

        public Criteria andComPhoneEqualTo(String value) {
            addCriterion("com_phone =", value, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneNotEqualTo(String value) {
            addCriterion("com_phone <>", value, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneGreaterThan(String value) {
            addCriterion("com_phone >", value, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("com_phone >=", value, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneLessThan(String value) {
            addCriterion("com_phone <", value, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneLessThanOrEqualTo(String value) {
            addCriterion("com_phone <=", value, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneLike(String value) {
            addCriterion("com_phone like", value, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneNotLike(String value) {
            addCriterion("com_phone not like", value, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneIn(List<String> values) {
            addCriterion("com_phone in", values, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneNotIn(List<String> values) {
            addCriterion("com_phone not in", values, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneBetween(String value1, String value2) {
            addCriterion("com_phone between", value1, value2, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComPhoneNotBetween(String value1, String value2) {
            addCriterion("com_phone not between", value1, value2, "comPhone");
            return (Criteria) this;
        }

        public Criteria andComEmailIsNull() {
            addCriterion("com_email is null");
            return (Criteria) this;
        }

        public Criteria andComEmailIsNotNull() {
            addCriterion("com_email is not null");
            return (Criteria) this;
        }

        public Criteria andComEmailEqualTo(String value) {
            addCriterion("com_email =", value, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailNotEqualTo(String value) {
            addCriterion("com_email <>", value, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailGreaterThan(String value) {
            addCriterion("com_email >", value, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailGreaterThanOrEqualTo(String value) {
            addCriterion("com_email >=", value, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailLessThan(String value) {
            addCriterion("com_email <", value, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailLessThanOrEqualTo(String value) {
            addCriterion("com_email <=", value, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailLike(String value) {
            addCriterion("com_email like", value, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailNotLike(String value) {
            addCriterion("com_email not like", value, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailIn(List<String> values) {
            addCriterion("com_email in", values, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailNotIn(List<String> values) {
            addCriterion("com_email not in", values, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailBetween(String value1, String value2) {
            addCriterion("com_email between", value1, value2, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComEmailNotBetween(String value1, String value2) {
            addCriterion("com_email not between", value1, value2, "comEmail");
            return (Criteria) this;
        }

        public Criteria andComCodeIsNull() {
            addCriterion("com_code is null");
            return (Criteria) this;
        }

        public Criteria andComCodeIsNotNull() {
            addCriterion("com_code is not null");
            return (Criteria) this;
        }

        public Criteria andComCodeEqualTo(String value) {
            addCriterion("com_code =", value, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeNotEqualTo(String value) {
            addCriterion("com_code <>", value, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeGreaterThan(String value) {
            addCriterion("com_code >", value, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeGreaterThanOrEqualTo(String value) {
            addCriterion("com_code >=", value, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeLessThan(String value) {
            addCriterion("com_code <", value, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeLessThanOrEqualTo(String value) {
            addCriterion("com_code <=", value, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeLike(String value) {
            addCriterion("com_code like", value, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeNotLike(String value) {
            addCriterion("com_code not like", value, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeIn(List<String> values) {
            addCriterion("com_code in", values, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeNotIn(List<String> values) {
            addCriterion("com_code not in", values, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeBetween(String value1, String value2) {
            addCriterion("com_code between", value1, value2, "comCode");
            return (Criteria) this;
        }

        public Criteria andComCodeNotBetween(String value1, String value2) {
            addCriterion("com_code not between", value1, value2, "comCode");
            return (Criteria) this;
        }

        public Criteria andComAddreIsNull() {
            addCriterion("com_addre is null");
            return (Criteria) this;
        }

        public Criteria andComAddreIsNotNull() {
            addCriterion("com_addre is not null");
            return (Criteria) this;
        }

        public Criteria andComAddreEqualTo(String value) {
            addCriterion("com_addre =", value, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreNotEqualTo(String value) {
            addCriterion("com_addre <>", value, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreGreaterThan(String value) {
            addCriterion("com_addre >", value, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreGreaterThanOrEqualTo(String value) {
            addCriterion("com_addre >=", value, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreLessThan(String value) {
            addCriterion("com_addre <", value, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreLessThanOrEqualTo(String value) {
            addCriterion("com_addre <=", value, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreLike(String value) {
            addCriterion("com_addre like", value, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreNotLike(String value) {
            addCriterion("com_addre not like", value, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreIn(List<String> values) {
            addCriterion("com_addre in", values, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreNotIn(List<String> values) {
            addCriterion("com_addre not in", values, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreBetween(String value1, String value2) {
            addCriterion("com_addre between", value1, value2, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComAddreNotBetween(String value1, String value2) {
            addCriterion("com_addre not between", value1, value2, "comAddre");
            return (Criteria) this;
        }

        public Criteria andComNoteIsNull() {
            addCriterion("com_note is null");
            return (Criteria) this;
        }

        public Criteria andComNoteIsNotNull() {
            addCriterion("com_note is not null");
            return (Criteria) this;
        }

        public Criteria andComNoteEqualTo(String value) {
            addCriterion("com_note =", value, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteNotEqualTo(String value) {
            addCriterion("com_note <>", value, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteGreaterThan(String value) {
            addCriterion("com_note >", value, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteGreaterThanOrEqualTo(String value) {
            addCriterion("com_note >=", value, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteLessThan(String value) {
            addCriterion("com_note <", value, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteLessThanOrEqualTo(String value) {
            addCriterion("com_note <=", value, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteLike(String value) {
            addCriterion("com_note like", value, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteNotLike(String value) {
            addCriterion("com_note not like", value, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteIn(List<String> values) {
            addCriterion("com_note in", values, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteNotIn(List<String> values) {
            addCriterion("com_note not in", values, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteBetween(String value1, String value2) {
            addCriterion("com_note between", value1, value2, "comNote");
            return (Criteria) this;
        }

        public Criteria andComNoteNotBetween(String value1, String value2) {
            addCriterion("com_note not between", value1, value2, "comNote");
            return (Criteria) this;
        }

        public Criteria andComUserIdIsNull() {
            addCriterion("com_user_id is null");
            return (Criteria) this;
        }

        public Criteria andComUserIdIsNotNull() {
            addCriterion("com_user_id is not null");
            return (Criteria) this;
        }

        public Criteria andComUserIdEqualTo(Integer value) {
            addCriterion("com_user_id =", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdNotEqualTo(Integer value) {
            addCriterion("com_user_id <>", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdGreaterThan(Integer value) {
            addCriterion("com_user_id >", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("com_user_id >=", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdLessThan(Integer value) {
            addCriterion("com_user_id <", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("com_user_id <=", value, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdIn(List<Integer> values) {
            addCriterion("com_user_id in", values, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdNotIn(List<Integer> values) {
            addCriterion("com_user_id not in", values, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdBetween(Integer value1, Integer value2) {
            addCriterion("com_user_id between", value1, value2, "comUserId");
            return (Criteria) this;
        }

        public Criteria andComUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("com_user_id not between", value1, value2, "comUserId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_info
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table company_info
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}