package com.zxm.graduatemanagesystem.model;

public class CompanyInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.com_name
     *
     * @mbggenerated
     */
    private String comName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.com_person
     *
     * @mbggenerated
     */
    private String comPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.com_phone
     *
     * @mbggenerated
     */
    private String comPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.com_email
     *
     * @mbggenerated
     */
    private String comEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.com_code
     *
     * @mbggenerated
     */
    private String comCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.com_addre
     *
     * @mbggenerated
     */
    private String comAddre;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.com_note
     *
     * @mbggenerated
     */
    private String comNote;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company_info.com_user_id
     *
     * @mbggenerated
     */
    private Integer comUserId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.id
     *
     * @return the value of company_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.id
     *
     * @param id the value for company_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.com_name
     *
     * @return the value of company_info.com_name
     *
     * @mbggenerated
     */
    public String getComName() {
        return comName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.com_name
     *
     * @param comName the value for company_info.com_name
     *
     * @mbggenerated
     */
    public void setComName(String comName) {
        this.comName = comName == null ? null : comName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.com_person
     *
     * @return the value of company_info.com_person
     *
     * @mbggenerated
     */
    public String getComPerson() {
        return comPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.com_person
     *
     * @param comPerson the value for company_info.com_person
     *
     * @mbggenerated
     */
    public void setComPerson(String comPerson) {
        this.comPerson = comPerson == null ? null : comPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.com_phone
     *
     * @return the value of company_info.com_phone
     *
     * @mbggenerated
     */
    public String getComPhone() {
        return comPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.com_phone
     *
     * @param comPhone the value for company_info.com_phone
     *
     * @mbggenerated
     */
    public void setComPhone(String comPhone) {
        this.comPhone = comPhone == null ? null : comPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.com_email
     *
     * @return the value of company_info.com_email
     *
     * @mbggenerated
     */
    public String getComEmail() {
        return comEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.com_email
     *
     * @param comEmail the value for company_info.com_email
     *
     * @mbggenerated
     */
    public void setComEmail(String comEmail) {
        this.comEmail = comEmail == null ? null : comEmail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.com_code
     *
     * @return the value of company_info.com_code
     *
     * @mbggenerated
     */
    public String getComCode() {
        return comCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.com_code
     *
     * @param comCode the value for company_info.com_code
     *
     * @mbggenerated
     */
    public void setComCode(String comCode) {
        this.comCode = comCode == null ? null : comCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.com_addre
     *
     * @return the value of company_info.com_addre
     *
     * @mbggenerated
     */
    public String getComAddre() {
        return comAddre;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.com_addre
     *
     * @param comAddre the value for company_info.com_addre
     *
     * @mbggenerated
     */
    public void setComAddre(String comAddre) {
        this.comAddre = comAddre == null ? null : comAddre.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.com_note
     *
     * @return the value of company_info.com_note
     *
     * @mbggenerated
     */
    public String getComNote() {
        return comNote;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.com_note
     *
     * @param comNote the value for company_info.com_note
     *
     * @mbggenerated
     */
    public void setComNote(String comNote) {
        this.comNote = comNote == null ? null : comNote.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company_info.com_user_id
     *
     * @return the value of company_info.com_user_id
     *
     * @mbggenerated
     */
    public Integer getComUserId() {
        return comUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company_info.com_user_id
     *
     * @param comUserId the value for company_info.com_user_id
     *
     * @mbggenerated
     */
    public void setComUserId(Integer comUserId) {
        this.comUserId = comUserId;
    }
}