package com.zxm.graduatemanagesystem.model;

import java.util.Date;

public class RecruitInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_info.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_info.title
     *
     * @mbggenerated
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_info.employ_type
     *
     * @mbggenerated
     */
    private Byte employType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_info.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_info.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_info.author_id
     *
     * @mbggenerated
     */
    private Integer authorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_info.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column recruit_info.content
     *
     * @mbggenerated
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_info.id
     *
     * @return the value of recruit_info.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_info.id
     *
     * @param id the value for recruit_info.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_info.title
     *
     * @return the value of recruit_info.title
     *
     * @mbggenerated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_info.title
     *
     * @param title the value for recruit_info.title
     *
     * @mbggenerated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_info.employ_type
     *
     * @return the value of recruit_info.employ_type
     *
     * @mbggenerated
     */
    public Byte getEmployType() {
        return employType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_info.employ_type
     *
     * @param employType the value for recruit_info.employ_type
     *
     * @mbggenerated
     */
    public void setEmployType(Byte employType) {
        this.employType = employType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_info.create_date
     *
     * @return the value of recruit_info.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_info.create_date
     *
     * @param createDate the value for recruit_info.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_info.end_date
     *
     * @return the value of recruit_info.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_info.end_date
     *
     * @param endDate the value for recruit_info.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_info.author_id
     *
     * @return the value of recruit_info.author_id
     *
     * @mbggenerated
     */
    public Integer getAuthorId() {
        return authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_info.author_id
     *
     * @param authorId the value for recruit_info.author_id
     *
     * @mbggenerated
     */
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_info.status
     *
     * @return the value of recruit_info.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_info.status
     *
     * @param status the value for recruit_info.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column recruit_info.content
     *
     * @return the value of recruit_info.content
     *
     * @mbggenerated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column recruit_info.content
     *
     * @param content the value for recruit_info.content
     *
     * @mbggenerated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}