package com.zxm.graduatemanagesystem.dao.mapper;

import com.zxm.graduatemanagesystem.model.RecruitInfo;
import com.zxm.graduatemanagesystem.model.RecruitInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecruitInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int countByExample(RecruitInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int deleteByExample(RecruitInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int insert(RecruitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int insertSelective(RecruitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    List<RecruitInfo> selectByExampleWithBLOBs(RecruitInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    List<RecruitInfo> selectByExample(RecruitInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    RecruitInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecruitInfo record, @Param("example") RecruitInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") RecruitInfo record, @Param("example") RecruitInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecruitInfo record, @Param("example") RecruitInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecruitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(RecruitInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecruitInfo record);

}
