package com.zxm.graduatemanagesystem.dao.mapper;

import com.zxm.graduatemanagesystem.model.RecruitMeeting;
import com.zxm.graduatemanagesystem.model.RecruitMeetingCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RecruitMeetingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int countByExample(RecruitMeetingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int deleteByExample(RecruitMeetingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int insert(RecruitMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int insertSelective(RecruitMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    List<RecruitMeeting> selectByExampleWithBLOBs(RecruitMeetingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    List<RecruitMeeting> selectByExample(RecruitMeetingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    RecruitMeeting selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") RecruitMeeting record, @Param("example") RecruitMeetingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") RecruitMeeting record, @Param("example") RecruitMeetingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") RecruitMeeting record, @Param("example") RecruitMeetingCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RecruitMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(RecruitMeeting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table recruit_meeting
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RecruitMeeting record);

    List<RecruitMeeting> getMeetingOrderByStartTime();
}
